version: 2.1

orbs:
  python: circleci/python@0.2.1
jobs:
  test-style:
    docker:
      - image: alpine/flake8:3.7.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Flake8
          command: flake8 agent/
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - test-style

