version: 2.1

orbs:
  python: circleci/python@0.2.1
jobs:
  test-style:
    docker:
      - image: alpine/flake8:3.7.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Flake8
          command: flake8 
  build-and-test-py3.8.2:
    docker:
      - image: python:3.8.2-slim-buster
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest discover
          name: Test

workflows:
  main:
    jobs:
      - test-style
      - build-and-test-py3.8.2

