version: 2.1

defaults: &defaults
  working_directory: ~/repo

jobs:
  test-style:
    <<: *defaults
    docker:
      - image: alpine/flake8:3.7.9
    steps:
      - checkout
      - run:
          name: Flake8
          command: flake8 
  test-bullseye:
    docker:
      - image: debian:bullseye-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -qq && apt-get install --no-install-recommends -y python3-dev python3 python3-apt python3-pip python3-setuptools python3-wheel gcc git g++ libapt-pkg-dev
      - run:
          name: Install python dependencies
          command: pip3 install -r requirements.txt
      - run:
          command: python3 -m unittest discover -p "*test.py"
          name: Test python 3 bullseye
  test-stretch:
    docker:
      - image: debian:stretch-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -qq && apt-get install --no-install-recommends -y python3-dev python3 python3-apt python3-pip python3-setuptools python3-wheel gcc git g++ libapt-pkg-dev
      - run:
          name: Install python dependencies
          command: pip3 install -r requirements.txt
      - run:
          command: python3 -m unittest discover -p "*test.py"
          name: Test python 3 stretch
  test-buster:
    docker:
      - image: debian:buster-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -qq && apt-get install --no-install-recommends -y python3-dev python3 python3-apt python3-pip python3-setuptools python3-wheel gcc git g++ libapt-pkg-dev
      - run:
          name: Install python dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Test python 3 buster
          command: python3 -m unittest discover -p "*test.py"
  build-debian-buster-amd64-snapshot:
    <<: *defaults
    docker:
      - image: debian:buster-slim
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            apt-get update -qq 
            apt-get install --no-install-recommends -y python3-dev python3 python3-apt python3-pip python3-setuptools python3-wheel gcc git g++ libapt-pkg-dev python3-venv dpkg-dev build-essential debhelper dh-systemd dh-virtualenv libffi-dev
      - run:
          name: Create and activate virtualenv
          command: |
            python3 -m venv ~/repo/venv
            source ~/repo/venv/bin/activate
      - run:
          name: Install python dependencies
          command: pip3 install -r requirements.txt
      - run: 
          name: Package
          command: |
            export DH_VIRTUALENV_INSTALL_ROOT=/opt/IT4smart
            dpkg-buildpackage -us -uc --host-arch amd64
      - store_artifacts:
          path: ~/
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/*
  build-debian-buster-i386-snapshot:
    <<: *defaults
    docker:
      - image: i386/debian:buster-slim
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            apt-get update -qq 
            apt-get install --no-install-recommends -y python3-dev python3 python3-apt python3-pip python3-setuptools python3-wheel gcc git g++ \
              libapt-pkg-dev python3-venv dpkg-dev build-essential debhelper dh-systemd dh-virtualenv libffi-dev
      #- run:
      #    name: Create and activate virtualenv
      #    command: |
      #      python3 -m venv ~/repo/venv
      #      source ~/repo/venv/bin/activate
      #- run:
      #    name: Install python dependencies
      #    command: pip3 install -r requirements.txt
      - run: 
          name: Package
          command: |
            export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            export GIT_COMMIT=${CIRCLE_SHA1:0:7}
            export DH_VIRTUALENV_INSTALL_ROOT=/opt/IT4smart
            dpkg-buildpackage -us -uc --host-arch i386 -v${GIT_TAG//v}+git-${GIT_COMMIT}
      - store_artifacts:
          path: ~/
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/*

workflows:
  main:
    jobs:
      - test-style
      - test-bullseye
      - test-buster
      - test-stretch
      - build-debian-buster-amd64-snapshot:
          requires:
            - test-style
            - test-buster
      - build-debian-buster-i386-snapshot:
          requires:
            - test-style
            - test-buster

